AllCops:
  Exclude:
    - 'tmp/**/*'
  TargetRubyVersion: 2.3

# Test describe blocks can be any size
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

# Require lines to fit in pull requests.
Metrics/LineLength:
  Max: 92

# Gtk+ has a lot of accessor method starting with get_ or set_
Naming/AccessorMethodName:
  Enabled: false

# GirFFI uses a ffi-something naming scheme.
Naming/FileName:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - x
    - y
    - xc
    - yc

# I like to have symbols always look like symbols
Style/SymbolArray:
  EnforcedStyle: brackets
